backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img # Media files will be stored in the repo under static/img
public_folder: /img

collections:
  - name: "oppurtunities"
    label: "Oppurtunities"
    folder: "src/pages/oppurtunities"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "oppurtunity-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}